import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" flex flex-col h-screen max-h-screen bg-page text-default-text ">
          <Navbar />
          <div className=" overflow-y-auto ">{children}</div>
        </div>
      </body>
    </html>
  );
}
